### ISSUE TITLE
Burnout Paradise Remastered

### ISSUE THREAD

**Issue by JUNIORGBJ** [Bo98/libbndl#1]
Works in Burnout Paradise Remastered (Nintendo Switch)?

0001.BUNDLE

bnd2

**Comment by burninrubber0** [comment]
The bundle format didn't change on Switch, so it should work fine, yes.

**Comment by Bo98** [comment]
Hmm, must have missed this notification.

Yes, I tested Nintendo Switch files in Apt Player back in June 2020 and it worked fine without any modifications needed to bundle reading. Writing should be fine too.

Compatibility was perhaps helped a bit by every BPR version identifying themselves as "PC", which is annoying but at least did mean no changes were required.
